#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Views\Shared\_CarFilter.cshtml"
    using AutoSiteProject.Models.ViewModels;
    
    #line default
    #line hidden
    using AutoSiteProject.UI;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/_CarFilter.cshtml")]
    public partial class _Views_Shared__CarFilter_cshtml : System.Web.Mvc.WebViewPage<CarAggregateFilterViewModel>
    {
        public _Views_Shared__CarFilter_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<link");

WriteAttribute("href", Tuple.Create(" href=\"", 85), Tuple.Create("\"", 110)
, Tuple.Create(Tuple.Create("", 92), Tuple.Create<System.Object, System.Int32>(Href("~/Content/Site.css")
, 92), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n<link");

WriteAttribute("href", Tuple.Create(" href=\"", 138), Tuple.Create("\"", 169)
, Tuple.Create(Tuple.Create("", 145), Tuple.Create<System.Object, System.Int32>(Href("~/Content/chosen.min.css")
, 145), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n\r\n<script");

WriteAttribute("src", Tuple.Create(" src=\"", 201), Tuple.Create("\"", 247)
, Tuple.Create(Tuple.Create("", 207), Tuple.Create<System.Object, System.Int32>(Href("~/scripts/jquery.unobtrusive-ajax.min.js")
, 207), false)
);

WriteLiteral("></script>\r\n<script");

WriteAttribute("src", Tuple.Create(" src=\"", 267), Tuple.Create("\"", 303)
, Tuple.Create(Tuple.Create("", 273), Tuple.Create<System.Object, System.Int32>(Href("~/scripts/chosen.jquery.min.js")
, 273), false)
);

WriteLiteral("></script>\r\n<script");

WriteAttribute("src", Tuple.Create(" src=\"", 323), Tuple.Create("\"", 361)
, Tuple.Create(Tuple.Create("", 329), Tuple.Create<System.Object, System.Int32>(Href("~/scripts/AutoSite/DataLoader.js")
, 329), false)
);

WriteLiteral("></script>\r\n<script");

WriteAttribute("src", Tuple.Create(" src=\"", 381), Tuple.Create("\"", 418)
, Tuple.Create(Tuple.Create("", 387), Tuple.Create<System.Object, System.Int32>(Href("~/scripts/AutoSite/CarFilter.js")
, 387), false)
);

WriteLiteral("></script>\r\n\r\n<div");

WriteLiteral(" class=\"filter-section\"");

WriteLiteral(" data-cars-url=\"");

            
            #line 12 "..\..\Views\Shared\_CarFilter.cshtml"
                                      Write(Url.Action("GetCars", "DataLoader"));

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral(" data-countries-url=\"");

            
            #line 12 "..\..\Views\Shared\_CarFilter.cshtml"
                                                                                                Write(Url.Action("GetCountries", "DataLoader"));

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral(" data-manufacturers-url=\"");

            
            #line 12 "..\..\Views\Shared\_CarFilter.cshtml"
                                                                                                                                                                   Write(Url.Action("GetManufacturersOfCountry", "DataLoader"));

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral(" data-carmodels-url=\"");

            
            #line 12 "..\..\Views\Shared\_CarFilter.cshtml"
                                                                                                                                                                                                                                               Write(Url.Action("GetCarModelsOfManufacturer", "DataLoader"));

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral(" data-carbodytype-url=\"");

            
            #line 12 "..\..\Views\Shared\_CarFilter.cshtml"
                                                                                                                                                                                                                                                                                                                              Write(Url.Action("GetBodyTypes", "DataLoader"));

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral(" data-caroptions-url=\"");

            
            #line 12 "..\..\Views\Shared\_CarFilter.cshtml"
                                                                                                                                                                                                                                                                                                                                                                                              Write(Url.Action("GetCarOptions", "DataLoader"));

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("        ");

            
            #line 14 "..\..\Views\Shared\_CarFilter.cshtml"
   Write(Html.LabelFor(m => m.CountryId, htmlAttributes: new { @class = "control-label col-md-2" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n        <div");

WriteLiteral(" class=\"col-md-10\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 16 "..\..\Views\Shared\_CarFilter.cshtml"
       Write(Html.DropDownListFor(m => m.CountryId, new SelectList(new List<CountryViewModel>(), "Id", "Name", Model.CountryId), "Select country", htmlAttributes: new { @class = "form-control country-picker", @data_initId = @Model.CountryId }));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("        ");

            
            #line 20 "..\..\Views\Shared\_CarFilter.cshtml"
   Write(Html.LabelFor(m => m.ManufacturerId, htmlAttributes: new { @class = "control-label col-md-2" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n        <div");

WriteLiteral(" class=\"col-md-10\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 22 "..\..\Views\Shared\_CarFilter.cshtml"
       Write(Html.DropDownListFor(m => m.ManufacturerId, new SelectList(new List<ManufacturerViewModel>(), "Id", "Name", Model.ManufacturerId), "Select manufacturer", htmlAttributes: new { @class = "form-control manufacturer-picker", @data_initId = @Model.ManufacturerId }));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("        ");

            
            #line 26 "..\..\Views\Shared\_CarFilter.cshtml"
   Write(Html.LabelFor(m => m.ModelId, htmlAttributes: new { @class = "control-label col-md-2" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n        <div");

WriteLiteral(" class=\"col-md-10\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 28 "..\..\Views\Shared\_CarFilter.cshtml"
       Write(Html.DropDownListFor(m => m.ModelId, new SelectList(new List<CarModelViewModel>(), "Id", "Name", Model.ModelId), "Select car model", htmlAttributes: new { @class = "form-control carmodel-picker", @data_initId = @Model.ModelId }));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("        ");

            
            #line 32 "..\..\Views\Shared\_CarFilter.cshtml"
   Write(Html.LabelFor(m => m.BodyTypeId, htmlAttributes: new { @class = "control-label col-md-2" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n        <div");

WriteLiteral(" class=\"col-md-10\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 34 "..\..\Views\Shared\_CarFilter.cshtml"
       Write(Html.DropDownListFor(m => m.BodyTypeId, new SelectList(new List<CarBodyTypeViewModel>(), "Id", "Name", Model.BodyTypeId), "Select car body type", htmlAttributes: new { @class = "form-control carbodytype-picker", @data_initId = @Model.BodyTypeId }));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("        ");

            
            #line 38 "..\..\Views\Shared\_CarFilter.cshtml"
   Write(Html.LabelFor(m => m.OptionsIds, htmlAttributes: new { @class = "control-label col-md-2" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n        <div");

WriteLiteral(" class=\"col-md-10\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 40 "..\..\Views\Shared\_CarFilter.cshtml"
       Write(Html.ListBoxFor(m => m.OptionsIds, new SelectList(Model.AvalibleCarOptions, "Id", "Name"), htmlAttributes: new { @class = "form-control caroptions-picker" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("        ");

            
            #line 44 "..\..\Views\Shared\_CarFilter.cshtml"
   Write(Html.LabelFor(m => m.Description, htmlAttributes: new { @class = "control-label col-md-2" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n        <div");

WriteLiteral(" class=\"col-md-10\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 46 "..\..\Views\Shared\_CarFilter.cshtml"
       Write(Html.TextBoxFor(m => m.Description, htmlAttributes: new { @class = "form-control description-picker" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n    </div>\r\n</div>\r\n");

        }
    }
}
#pragma warning restore 1591
