#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Views\Shared\_CarFilter.cshtml"
    using AutoSiteProject.Models.ViewModels;
    
    #line default
    #line hidden
    using AutoSiteProject.UI;
    
    #line 2 "..\..\Views\Shared\_CarFilter.cshtml"
    using AutoSiteProject.UI.Helpers;
    
    #line default
    #line hidden
    using DevExpress.Utils;
    using DevExpress.Web;
    using DevExpress.Web.ASPxThemes;
    using DevExpress.Web.Mvc;
    using DevExpress.Web.Mvc.UI;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/_CarFilter.cshtml")]
    public partial class _Views_Shared__CarFilter_cshtml : System.Web.Mvc.WebViewPage<CarAggregateFilterViewModel>
    {
        public _Views_Shared__CarFilter_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<link");

WriteAttribute("href", Tuple.Create(" href=\"", 120), Tuple.Create("\"", 151)
, Tuple.Create(Tuple.Create("", 127), Tuple.Create<System.Object, System.Int32>(Href("~/Content/chosen.min.css")
, 127), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n<link");

WriteAttribute("href", Tuple.Create(" href=\"", 179), Tuple.Create("\"", 221)
, Tuple.Create(Tuple.Create("", 186), Tuple.Create<System.Object, System.Int32>(Href("~/Content/MyCss/CarFilterStyles.css")
, 186), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n\r\n<script");

WriteAttribute("src", Tuple.Create(" src=\"", 253), Tuple.Create("\"", 289)
, Tuple.Create(Tuple.Create("", 259), Tuple.Create<System.Object, System.Int32>(Href("~/scripts/chosen.jquery.min.js")
, 259), false)
);

WriteLiteral("></script>\r\n<script");

WriteAttribute("src", Tuple.Create(" src=\"", 309), Tuple.Create("\"", 347)
, Tuple.Create(Tuple.Create("", 315), Tuple.Create<System.Object, System.Int32>(Href("~/scripts/AutoSite/DataLoader.js")
, 315), false)
);

WriteLiteral("></script>\r\n<script");

WriteAttribute("src", Tuple.Create(" src=\"", 367), Tuple.Create("\"", 404)
, Tuple.Create(Tuple.Create("", 373), Tuple.Create<System.Object, System.Int32>(Href("~/scripts/AutoSite/CarFilter.js")
, 373), false)
);

WriteLiteral("></script>\r\n\r\n<div");

WriteLiteral(" id=\"filterPanel\"");

WriteLiteral(" class=\"filterPanel\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"list-group panel\"");

WriteLiteral(">\r\n        <a");

WriteLiteral(" href=\"#filterForm\"");

WriteLiteral(" class=\"list-group-item list-group-item-success strong\"");

WriteLiteral(" data-toggle=\"collapse\"");

WriteLiteral(" data-parent=\"#filterPanel\"");

WriteLiteral(">Filter<i");

WriteLiteral(" class=\"fa fa-caret-down\"");

WriteLiteral("></i></a>\r\n        <div");

WriteLiteral(" class=\"collapse in\"");

WriteLiteral(" id=\"filterForm\"");

WriteLiteral(">\r\n            <form");

WriteLiteral(" class=\"form-inline width100\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"filter-section width100\"");

WriteLiteral("\r\n                     data-cars-url=\"");

            
            #line 18 "..\..\Views\Shared\_CarFilter.cshtml"
                               Write(Url.Action("GetCars", "DataLoader"));

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral("\r\n                     data-countries-url=\"");

            
            #line 19 "..\..\Views\Shared\_CarFilter.cshtml"
                                    Write(Url.Action("GetCountries", "DataLoader"));

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral("\r\n                     data-manufacturers-url=\"");

            
            #line 20 "..\..\Views\Shared\_CarFilter.cshtml"
                                        Write(Url.Action("GetManufacturersOfCountry", "DataLoader"));

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral("\r\n                     data-carmodels-url=\"");

            
            #line 21 "..\..\Views\Shared\_CarFilter.cshtml"
                                    Write(Url.Action("GetCarModelsOfManufacturer", "DataLoader"));

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral("\r\n                     data-carbodytype-url=\"");

            
            #line 22 "..\..\Views\Shared\_CarFilter.cshtml"
                                      Write(Url.Action("GetBodyTypes", "DataLoader"));

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral("\r\n                     data-carfueltype-url=\"");

            
            #line 23 "..\..\Views\Shared\_CarFilter.cshtml"
                                      Write(Url.Action("GetFuelTypes", "DataLoader"));

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral("\r\n                     data-cartransmitiontype-url=\"");

            
            #line 24 "..\..\Views\Shared\_CarFilter.cshtml"
                                             Write(Url.Action("GetTransmitionTypes", "DataLoader"));

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral("\r\n                     data-caroptions-url=\"");

            
            #line 25 "..\..\Views\Shared\_CarFilter.cshtml"
                                     Write(Url.Action("GetCarOptions", "DataLoader"));

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral(">\r\n\r\n                    ");

WriteLiteral("\r\n                    <div");

WriteLiteral(" class=\"form-group width100\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 33 "..\..\Views\Shared\_CarFilter.cshtml"
                   Write(Html.LabelFor(m => m.AllFieldsSearch, htmlAttributes: new { @class = "control-label col-sm-4" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        <div");

WriteLiteral(" class=\"col-sm-2 width100\"");

WriteLiteral(">\r\n");

WriteLiteral("                            ");

            
            #line 35 "..\..\Views\Shared\_CarFilter.cshtml"
                       Write(Html.SearchFor(m => m.AllFieldsSearch, htmlAttributes: new { @class = "form-control allFields-picker width100" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </div>\r\n                    </div>\r\n                   " +
" <div");

WriteLiteral(" class=\"form-group width33\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 39 "..\..\Views\Shared\_CarFilter.cshtml"
                   Write(Html.LabelFor(m => m.CountryId, htmlAttributes: new { @class = "control-label col-sm-4" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        <div");

WriteLiteral(" class=\"col-sm-10 width100\"");

WriteLiteral(">\r\n");

WriteLiteral("                            ");

            
            #line 41 "..\..\Views\Shared\_CarFilter.cshtml"
                       Write(Html.DropDownListFor(m => m.CountryId, new SelectList(new List<CountryViewModel>(), "Id", "Name", Model.CountryId), "Select country", htmlAttributes: new { @class = "form-control country-picker width100", @data_initId = @Model.CountryId }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </div>\r\n                    </div>\r\n                   " +
" <div");

WriteLiteral(" class=\"form-group width33\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 45 "..\..\Views\Shared\_CarFilter.cshtml"
                   Write(Html.LabelFor(m => m.ManufacturerId, htmlAttributes: new { @class = "control-label col-sm-4" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        <div");

WriteLiteral(" class=\"col-sm-10 width100\"");

WriteLiteral(">\r\n");

WriteLiteral("                            ");

            
            #line 47 "..\..\Views\Shared\_CarFilter.cshtml"
                       Write(Html.DropDownListFor(m => m.ManufacturerId, new SelectList(new List<ManufacturerViewModel>(), "Id", "Name", Model.ManufacturerId), "Select manufacturer", htmlAttributes: new { @class = "form-control manufacturer-picker width100", @data_initId = @Model.ManufacturerId }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </div>\r\n                    </div>\r\n                   " +
" <div");

WriteLiteral(" class=\"form-group width33\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 51 "..\..\Views\Shared\_CarFilter.cshtml"
                   Write(Html.LabelFor(m => m.ModelId, htmlAttributes: new { @class = "control-label col-sm-4" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        <div");

WriteLiteral(" class=\"col-sm-10 width100\"");

WriteLiteral(">\r\n");

WriteLiteral("                            ");

            
            #line 53 "..\..\Views\Shared\_CarFilter.cshtml"
                       Write(Html.DropDownListFor(m => m.ModelId, new SelectList(new List<CarModelViewModel>(), "Id", "Name", Model.ModelId), "Select car model", htmlAttributes: new { @class = "form-control carmodel-picker width100", @data_initId = @Model.ModelId }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </div>\r\n                    </div>\r\n                   " +
" <div");

WriteLiteral(" class=\"form-group width33\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 57 "..\..\Views\Shared\_CarFilter.cshtml"
                   Write(Html.LabelFor(m => m.BodyTypeId, htmlAttributes: new { @class = "control-label col-sm-4" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        <div");

WriteLiteral(" class=\"col-sm-10 width100\"");

WriteLiteral(">\r\n");

WriteLiteral("                            ");

            
            #line 59 "..\..\Views\Shared\_CarFilter.cshtml"
                       Write(Html.DropDownListFor(m => m.BodyTypeId, new SelectList(new List<CarBodyTypeViewModel>(), "Id", "Name", Model.BodyTypeId), "Select car body type", htmlAttributes: new { @class = "form-control carbodytype-picker width100", @data_initId = @Model.BodyTypeId }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </div>\r\n                    </div>\r\n                   " +
" <div");

WriteLiteral(" class=\"form-group width33\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 63 "..\..\Views\Shared\_CarFilter.cshtml"
                   Write(Html.LabelFor(m => m.FuelTypeId, htmlAttributes: new { @class = "control-label col-md-2" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        <div");

WriteLiteral(" class=\"col-md-10 width100\"");

WriteLiteral(">\r\n");

WriteLiteral("                            ");

            
            #line 65 "..\..\Views\Shared\_CarFilter.cshtml"
                       Write(Html.DropDownListFor(m => m.FuelTypeId, new SelectList(new List<FuelTypeViewModel>(), "Id", "Name", Model.FuelTypeId), "Select car fuel type", htmlAttributes: new { @class = "form-control carfueltype-picker", @data_initId = @Model.FuelTypeId }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                            ");

            
            #line 66 "..\..\Views\Shared\_CarFilter.cshtml"
                       Write(Html.ValidationMessageFor(model => model.FuelTypeId, "", new { @class = "text-danger" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </div>\r\n                    </div>\r\n                   " +
" <div");

WriteLiteral(" class=\"form-group width33\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 70 "..\..\Views\Shared\_CarFilter.cshtml"
                   Write(Html.LabelFor(m => m.TransmitionTypeId, htmlAttributes: new { @class = "control-label col-md-2" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        <div");

WriteLiteral(" class=\"col-md-10 width100\"");

WriteLiteral(">\r\n");

WriteLiteral("                            ");

            
            #line 72 "..\..\Views\Shared\_CarFilter.cshtml"
                       Write(Html.DropDownListFor(m => m.TransmitionTypeId, new SelectList(new List<TransmitionTypeViewModel>(), "Id", "Name", Model.TransmitionTypeId), "Select car transmition type", htmlAttributes: new { @class = "form-control cartransmitiontype-picker", @data_initId = @Model.TransmitionTypeId }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                            ");

            
            #line 73 "..\..\Views\Shared\_CarFilter.cshtml"
                       Write(Html.ValidationMessageFor(model => model.TransmitionTypeId, "", new { @class = "text-danger" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </div>\r\n                    </div>\r\n                   " +
" <div");

WriteLiteral(" class=\"form-group width33\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 77 "..\..\Views\Shared\_CarFilter.cshtml"
                   Write(Html.LabelFor(m => m.OptionsIds, htmlAttributes: new { @class = "control-label col-sm-4" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        <div");

WriteLiteral(" class=\"col-sm-10 width100\"");

WriteLiteral(">\r\n");

WriteLiteral("                            ");

            
            #line 79 "..\..\Views\Shared\_CarFilter.cshtml"
                       Write(Html.ListBoxFor(m => m.OptionsIds, new SelectList(Model.AvalibleCarOptions, "Id", "Name"), htmlAttributes: new { @class = "form-control caroptions-picker width100" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </div>\r\n                    </div>\r\n                   " +
" <div");

WriteLiteral(" class=\"form-group width33\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 83 "..\..\Views\Shared\_CarFilter.cshtml"
                   Write(Html.LabelFor(m => m.ReleaseYearMin, "Release year:"+Model.ReleaseYearMin+"-"+Model.ReleaseYearMax,htmlAttributes: new { @class = "control-label col-md-2 releaseyear-label width100" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        <div");

WriteLiteral(" class=\"col-md-10 widht100\"");

WriteLiteral(">\r\n");

WriteLiteral("                            ");

            
            #line 85 "..\..\Views\Shared\_CarFilter.cshtml"
                       Write(Html.HiddenFor(m => m.ReleaseYearMin));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                            ");

            
            #line 86 "..\..\Views\Shared\_CarFilter.cshtml"
                       Write(Html.HiddenFor(m => m.ReleaseYearMax));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                            ");

            
            #line 87 "..\..\Views\Shared\_CarFilter.cshtml"
                       Write(Html.ValidationMessageFor(model => model.ReleaseYearMin, "", new {@class = "text-danger"}));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                            ");

            
            #line 88 "..\..\Views\Shared\_CarFilter.cshtml"
                       Write(Html.ValidationMessageFor(model => model.ReleaseYearMax, "", new {@class = "text-danger"}));

            
            #line default
            #line hidden
WriteLiteral("\r\n                            <div");

WriteLiteral(" class=\"releaseyear-range-slider width100\"");

WriteLiteral(">\r\n                            </div>\r\n                        </div>\r\n          " +
"          </div>\r\n\r\n                    <div");

WriteLiteral(" class=\"form-group width33\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 95 "..\..\Views\Shared\_CarFilter.cshtml"
                   Write(Html.LabelFor(m => m.VolumeMin,"Engine volume:"+Model.VolumeMin+"-"+Model.VolumeMax, htmlAttributes: new { @class = "control-label col-md-2 volume-label width100" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        <div");

WriteLiteral(" class=\"col-md-10 width100\"");

WriteLiteral(">\r\n");

WriteLiteral("                            ");

            
            #line 97 "..\..\Views\Shared\_CarFilter.cshtml"
                       Write(Html.HiddenFor(m => m.VolumeMin));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                            ");

            
            #line 98 "..\..\Views\Shared\_CarFilter.cshtml"
                       Write(Html.HiddenFor(m => m.VolumeMax));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                            ");

            
            #line 99 "..\..\Views\Shared\_CarFilter.cshtml"
                       Write(Html.ValidationMessageFor(model => model.VolumeMin, "", new { @class = "text-danger" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                            ");

            
            #line 100 "..\..\Views\Shared\_CarFilter.cshtml"
                       Write(Html.ValidationMessageFor(model => model.VolumeMax, "", new { @class = "text-danger" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                            <div");

WriteLiteral(" class=\"volume-range-slider\"");

WriteLiteral(">\r\n\r\n                            </div>\r\n                        </div>\r\n        " +
"            </div>\r\n                    <div");

WriteLiteral(" class=\"form-group width33\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 107 "..\..\Views\Shared\_CarFilter.cshtml"
                   Write(Html.LabelFor(m => m.PriceMin,"Price:"+Model.PriceMin+"-"+Model.PriceMax, htmlAttributes: new { @class = "control-label col-md-2 price-label width100" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        <div");

WriteLiteral(" class=\"col-md-10 width100\"");

WriteLiteral(">\r\n");

WriteLiteral("                            ");

            
            #line 109 "..\..\Views\Shared\_CarFilter.cshtml"
                       Write(Html.HiddenFor(m => m.PriceMin));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                            ");

            
            #line 110 "..\..\Views\Shared\_CarFilter.cshtml"
                       Write(Html.HiddenFor(m => m.PriceMax));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                            ");

            
            #line 111 "..\..\Views\Shared\_CarFilter.cshtml"
                       Write(Html.ValidationMessageFor(model => model.PriceMin, "", new { @class = "text-danger" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                            ");

            
            #line 112 "..\..\Views\Shared\_CarFilter.cshtml"
                       Write(Html.ValidationMessageFor(model => model.PriceMax, "", new { @class = "text-danger" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                            <div");

WriteLiteral(" class=\"price-range-slider\"");

WriteLiteral(">\r\n\r\n                            </div>\r\n\r\n                        </div>\r\n      " +
"              </div>\r\n                    <div");

WriteLiteral(" class=\"form-group width33\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 120 "..\..\Views\Shared\_CarFilter.cshtml"
                   Write(Html.LabelFor(m => m.Description, htmlAttributes: new { @class = "control-label col-sm-4" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        <div");

WriteLiteral(" class=\"col-sm-10 width100\"");

WriteLiteral(">\r\n");

WriteLiteral("                            ");

            
            #line 122 "..\..\Views\Shared\_CarFilter.cshtml"
                       Write(Html.TextBoxFor(m => m.Description, htmlAttributes: new { @class = "form-control description-picker width100" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </div>\r\n                    </div>\r\n                </d" +
"iv>\r\n            </form>\r\n        </div>\r\n    </div>\r\n</div>\r\n");

        }
    }
}
#pragma warning restore 1591
