#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Views\Shared\_CarItem.cshtml"
    using AutoSiteProject.Models.ViewModels;
    
    #line default
    #line hidden
    using AutoSiteProject.UI;
    using DevExpress.Utils;
    using DevExpress.Web;
    using DevExpress.Web.ASPxThemes;
    using DevExpress.Web.Mvc;
    using DevExpress.Web.Mvc.UI;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/_CarItem.cshtml")]
    public partial class _Views_Shared__CarItem_cshtml : System.Web.Mvc.WebViewPage<CarItemViewModel>
    {
        public _Views_Shared__CarItem_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<link");

WriteAttribute("href", Tuple.Create(" href=\"", 74), Tuple.Create("\"", 99)
, Tuple.Create(Tuple.Create("", 81), Tuple.Create<System.Object, System.Int32>(Href("~/Content/Site.css")
, 81), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n<link");

WriteAttribute("href", Tuple.Create(" href=\"", 127), Tuple.Create("\"", 158)
, Tuple.Create(Tuple.Create("", 134), Tuple.Create<System.Object, System.Int32>(Href("~/Content/chosen.min.css")
, 134), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n<script");

WriteAttribute("src", Tuple.Create(" src=\"", 188), Tuple.Create("\"", 234)
, Tuple.Create(Tuple.Create("", 194), Tuple.Create<System.Object, System.Int32>(Href("~/scripts/jquery.unobtrusive-ajax.min.js")
, 194), false)
);

WriteLiteral("></script>\r\n<script");

WriteAttribute("src", Tuple.Create(" src=\"", 254), Tuple.Create("\"", 290)
, Tuple.Create(Tuple.Create("", 260), Tuple.Create<System.Object, System.Int32>(Href("~/scripts/chosen.jquery.min.js")
, 260), false)
);

WriteLiteral("></script>\r\n<script");

WriteAttribute("src", Tuple.Create(" src=\"", 310), Tuple.Create("\"", 348)
, Tuple.Create(Tuple.Create("", 316), Tuple.Create<System.Object, System.Int32>(Href("~/scripts/AutoSite/DataLoader.js")
, 316), false)
);

WriteLiteral("></script>\r\n\r\n<hr />\r\n<div");

WriteLiteral(" class=\"filter-section\"");

WriteLiteral(" data-countries-url=\"");

            
            #line 11 "..\..\Views\Shared\_CarItem.cshtml"
                                           Write(Url.Action("GetCountries", "DataLoader"));

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral(" data-manufacturers-url=\"");

            
            #line 11 "..\..\Views\Shared\_CarItem.cshtml"
                                                                                                              Write(Url.Action("GetManufacturersOfCountry", "DataLoader"));

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral(" data-carmodels-url=\"");

            
            #line 11 "..\..\Views\Shared\_CarItem.cshtml"
                                                                                                                                                                                          Write(Url.Action("GetCarModelsOfManufacturer", "DataLoader"));

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral(" data-carbodytype-url=\"");

            
            #line 11 "..\..\Views\Shared\_CarItem.cshtml"
                                                                                                                                                                                                                                                                         Write(Url.Action("GetBodyTypes", "DataLoader"));

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral(" data-caroptions-url=\"");

            
            #line 11 "..\..\Views\Shared\_CarItem.cshtml"
                                                                                                                                                                                                                                                                                                                                         Write(Url.Action("GetCarOptions", "DataLoader"));

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral(">\r\n");

WriteLiteral("    ");

            
            #line 12 "..\..\Views\Shared\_CarItem.cshtml"
Write(Html.HiddenFor(model => model.Id));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 13 "..\..\Views\Shared\_CarItem.cshtml"
Write(Html.ValidationSummary(true, "", new { @class = "text-danger" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n    <div");

WriteLiteral(" class=\"form-group \"");

WriteLiteral(">\r\n");

WriteLiteral("        ");

            
            #line 15 "..\..\Views\Shared\_CarItem.cshtml"
   Write(Html.LabelFor(m => m.CountryId, htmlAttributes: new { @class = "control-label col-md-2" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n        <div");

WriteLiteral(" class=\"col-md-10\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 17 "..\..\Views\Shared\_CarItem.cshtml"
       Write(Html.DropDownListFor(m => m.CountryId, new SelectList(new List<CountryViewModel>(), "Id", "Name", Model.CountryId), "Select country", htmlAttributes: new { @class = "form-control country-picker", @data_initId = @Model.CountryId }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("            ");

            
            #line 18 "..\..\Views\Shared\_CarItem.cshtml"
       Write(Html.ValidationMessageFor(model => model.CountryId, "", new { @class = "text-danger" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"form-group widht50\"");

WriteLiteral(">\r\n");

WriteLiteral("        ");

            
            #line 22 "..\..\Views\Shared\_CarItem.cshtml"
   Write(Html.LabelFor(m => m.ManufacturerId, htmlAttributes: new { @class = "control-label col-md-2" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n        <div");

WriteLiteral(" class=\"col-md-10 \"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 24 "..\..\Views\Shared\_CarItem.cshtml"
       Write(Html.DropDownListFor(m => m.ManufacturerId, new SelectList(new List<ManufacturerViewModel>(), "Id", "Name", Model.ManufacturerId), "Select manufacturer", htmlAttributes: new { @class = "form-control manufacturer-picker", @data_initId = @Model.ManufacturerId }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("            ");

            
            #line 25 "..\..\Views\Shared\_CarItem.cshtml"
       Write(Html.ValidationMessageFor(model => model.ManufacturerId, "", new { @class = "text-danger" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("        ");

            
            #line 29 "..\..\Views\Shared\_CarItem.cshtml"
   Write(Html.LabelFor(m => m.ModelId, htmlAttributes: new { @class = "control-label col-md-2" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n        <div");

WriteLiteral(" class=\"col-md-10\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 31 "..\..\Views\Shared\_CarItem.cshtml"
       Write(Html.DropDownListFor(m => m.ModelId, new SelectList(new List<CarModelViewModel>(), "Id", "Name", Model.ModelId), "Select car model", htmlAttributes: new { @class = "form-control carmodel-picker", @data_initId = @Model.ModelId }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("            ");

            
            #line 32 "..\..\Views\Shared\_CarItem.cshtml"
       Write(Html.ValidationMessageFor(model => model.ModelId, "", new { @class = "text-danger" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("        ");

            
            #line 36 "..\..\Views\Shared\_CarItem.cshtml"
   Write(Html.LabelFor(m => m.BodyTypeId, htmlAttributes: new { @class = "control-label col-md-2" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n        <div");

WriteLiteral(" class=\"col-md-10\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 38 "..\..\Views\Shared\_CarItem.cshtml"
       Write(Html.DropDownListFor(m => m.BodyTypeId, new SelectList(new List<CarBodyTypeViewModel>(), "Id", "Name", Model.BodyTypeId), "Select car body type", htmlAttributes: new { @class = "form-control carbodytype-picker", @data_initId = @Model.BodyTypeId }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("            ");

            
            #line 39 "..\..\Views\Shared\_CarItem.cshtml"
       Write(Html.ValidationMessageFor(model => model.BodyTypeId, "", new { @class = "text-danger" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("        ");

            
            #line 43 "..\..\Views\Shared\_CarItem.cshtml"
   Write(Html.LabelFor(m => m.SelectedCarOptions, htmlAttributes: new { @class = "control-label col-md-2" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n        <div");

WriteLiteral(" class=\"col-md-10\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 45 "..\..\Views\Shared\_CarItem.cshtml"
       Write(Html.ListBoxFor(m => m.SelectedCarOptions, new SelectList(Model.AvalibleCarOptions, "Id", "Name"), htmlAttributes: new { @class = "form-control caroptions-picker" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("        ");

            
            #line 49 "..\..\Views\Shared\_CarItem.cshtml"
   Write(Html.LabelFor(m => m.Description, htmlAttributes: new { @class = "control-label col-md-2" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n        <div");

WriteLiteral(" class=\"col-md-10\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 51 "..\..\Views\Shared\_CarItem.cshtml"
       Write(Html.EditorFor(m => m.Description, new { htmlAttributes = new { @class = "form-control" } }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("            ");

            
            #line 52 "..\..\Views\Shared\_CarItem.cshtml"
       Write(Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n    </div>\r\n</div>\r\n");

        }
    }
}
#pragma warning restore 1591
