#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using AutoSiteProject.UI;
    
    #line 1 "..\..\Views\Shared\_Layout.cshtml"
    using AutoSiteProject.UI.Helpers;
    
    #line default
    #line hidden
    using DevExpress.Utils;
    using DevExpress.Web;
    using DevExpress.Web.ASPxThemes;
    using DevExpress.Web.Mvc;
    using DevExpress.Web.Mvc.UI;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/_Layout.cshtml")]
    public partial class _Views_Shared__Layout_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Shared__Layout_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<!DOCTYPE html>\r\n<html>\r\n<head>\r\n    <meta");

WriteLiteral(" charset=\"utf-8\"");

WriteLiteral(" />\r\n    <meta");

WriteLiteral(" name=\"viewport\"");

WriteLiteral(" content=\"width=device-width, initial-scale=1.0\"");

WriteLiteral(">\r\n    <title>AutoSiteProject</title>\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 219), Tuple.Create("\"", 255)
, Tuple.Create(Tuple.Create("", 226), Tuple.Create<System.Object, System.Int32>(Href("~/Content/css/select2.min.css")
, 226), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 287), Tuple.Create("\"", 321)
, Tuple.Create(Tuple.Create("", 294), Tuple.Create<System.Object, System.Int32>(Href("~/Content/bootstrap.min.css")
, 294), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(" />\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 369), Tuple.Create("\"", 415)
, Tuple.Create(Tuple.Create("", 376), Tuple.Create<System.Object, System.Int32>(Href("~/Content/themes/base/jquery-ui.min.css")
, 376), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 451), Tuple.Create("\"", 487)
, Tuple.Create(Tuple.Create("", 457), Tuple.Create<System.Object, System.Int32>(Href("~/scripts/jquery-1.10.2.min.js")
, 457), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 511), Tuple.Create("\"", 549)
, Tuple.Create(Tuple.Create("", 517), Tuple.Create<System.Object, System.Int32>(Href("~/scripts/jquery.validate.min.js")
, 517), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 573), Tuple.Create("\"", 623)
, Tuple.Create(Tuple.Create("", 579), Tuple.Create<System.Object, System.Int32>(Href("~/scripts/jquery.validate.unobtrusive.min.js")
, 579), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 647), Tuple.Create("\"", 693)
, Tuple.Create(Tuple.Create("", 653), Tuple.Create<System.Object, System.Int32>(Href("~/scripts/jquery.unobtrusive-ajax.min.js")
, 653), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 717), Tuple.Create("\"", 751)
, Tuple.Create(Tuple.Create("", 723), Tuple.Create<System.Object, System.Int32>(Href("~/scripts/modernizr-2.7.2.js")
, 723), false)
);

WriteLiteral("></script>\r\n");

WriteLiteral("    ");

            
            #line 17 "..\..\Views\Shared\_Layout.cshtml"
Write(Html.DevExpress().GetScripts(
        //new Script { ExtensionSuite = ExtensionSuite.NavigationAndLayout },
        //new Script { ExtensionSuite = ExtensionSuite.HtmlEditor },
        //new Script { ExtensionSuite = ExtensionSuite.PivotGrid },
        //new Script { ExtensionSuite = ExtensionSuite.Editors },
        //new Script { ExtensionSuite = ExtensionSuite.Chart },
        //new Script { ExtensionSuite = ExtensionSuite.Report },
        new Script { ExtensionSuite = ExtensionSuite.Scheduler },
        //new Script { ExtensionSuite = ExtensionSuite.TreeList },
        //new Script { ExtensionSuite = ExtensionSuite.Spreadsheet },
        //new Script { ExtensionSuite = ExtensionSuite.RichEdit },
        //new Script { ExtensionSuite = ExtensionSuite.SpellChecker },
        new Script { ExtensionSuite = ExtensionSuite.GridView }

    ));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 32 "..\..\Views\Shared\_Layout.cshtml"
Write(Html.DevExpress().GetStyleSheets(
        //new StyleSheet { ExtensionSuite = ExtensionSuite.NavigationAndLayout },
        //new StyleSheet { ExtensionSuite = ExtensionSuite.Editors },
        //new StyleSheet { ExtensionSuite = ExtensionSuite.HtmlEditor },
        //new StyleSheet { ExtensionSuite = ExtensionSuite.PivotGrid },
        //new StyleSheet { ExtensionSuite = ExtensionSuite.Chart },
        //new StyleSheet { ExtensionSuite = ExtensionSuite.Report },
        new StyleSheet { ExtensionSuite = ExtensionSuite.Scheduler },
        //new StyleSheet { ExtensionSuite = ExtensionSuite.TreeList },
        //new StyleSheet { ExtensionSuite = ExtensionSuite.Spreadsheet },
        //new StyleSheet { ExtensionSuite = ExtensionSuite.RichEdit },
        //new StyleSheet { ExtensionSuite = ExtensionSuite.SpellChecker },
        new StyleSheet { ExtensionSuite = ExtensionSuite.GridView }

    ));

            
            #line default
            #line hidden
WriteLiteral("\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 2571), Tuple.Create("\"", 2603)
, Tuple.Create(Tuple.Create("", 2577), Tuple.Create<System.Object, System.Int32>(Href("~/scripts/bootstrap.min.js")
, 2577), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 2627), Tuple.Create("\"", 2657)
, Tuple.Create(Tuple.Create("", 2633), Tuple.Create<System.Object, System.Int32>(Href("~/scripts/select2.min.js")
, 2633), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 2681), Tuple.Create("\"", 2724)
, Tuple.Create(Tuple.Create("", 2687), Tuple.Create<System.Object, System.Int32>(Href("~/scripts/AutoSite/MySelect2Search.js")
, 2687), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 2748), Tuple.Create("\"", 2791)
, Tuple.Create(Tuple.Create("", 2754), Tuple.Create<System.Object, System.Int32>(Href("~/scripts/jquery.signalR-2.2.0.min.js")
, 2754), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 2815), Tuple.Create("\"", 2835)
, Tuple.Create(Tuple.Create("", 2821), Tuple.Create<System.Object, System.Int32>(Href("~/signalr/hubs")
, 2821), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 2859), Tuple.Create("\"", 2900)
, Tuple.Create(Tuple.Create("", 2865), Tuple.Create<System.Object, System.Int32>(Href("~/scripts/AutoSite/Notifications.js")
, 2865), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 2924), Tuple.Create("\"", 2963)
, Tuple.Create(Tuple.Create("", 2930), Tuple.Create<System.Object, System.Int32>(Href("~/scripts/jquery-ui-1.12.0.min.js")
, 2930), false)
);

WriteLiteral("></script>\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 2985), Tuple.Create("\"", 3010)
, Tuple.Create(Tuple.Create("", 2992), Tuple.Create<System.Object, System.Int32>(Href("~/Content/Site.css")
, 2992), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" type=\"text/css\"");

WriteLiteral("/>\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 3057), Tuple.Create("\"", 3096)
, Tuple.Create(Tuple.Create("", 3064), Tuple.Create<System.Object, System.Int32>(Href("~/Content/MyCss/WidthClasses.css")
, 3064), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 3128), Tuple.Create("\"", 3168)
, Tuple.Create(Tuple.Create("", 3135), Tuple.Create<System.Object, System.Int32>(Href("~/Content/MyCss/Select2Styles.css")
, 3135), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n</head>\r\n<body>\r\n    <nav");

WriteLiteral(" class=\"navbar navbar-inverse navbar-fixed-top\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"navbar-collapse collapse\"");

WriteLiteral(">\r\n            <ul");

WriteLiteral(" class=\"nav navbar-nav\"");

WriteLiteral(">\r\n                <li>");

            
            #line 62 "..\..\Views\Shared\_Layout.cshtml"
               Write(Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "" }));

            
            #line default
            #line hidden
WriteLiteral("</li>\r\n                <li>");

            
            #line 63 "..\..\Views\Shared\_Layout.cshtml"
               Write(Html.ActionLink("Cars", "List", "CarItem", new { area = "" }, new { @class = "" }));

            
            #line default
            #line hidden
WriteLiteral("</li>\r\n");

            
            #line 64 "..\..\Views\Shared\_Layout.cshtml"
                
            
            #line default
            #line hidden
            
            #line 64 "..\..\Views\Shared\_Layout.cshtml"
                 if (User.IsInRole("Admin"))
                {

            
            #line default
            #line hidden
WriteLiteral("                    <li");

WriteLiteral(" class=\"dropdown\"");

WriteLiteral(">\r\n                        <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" class=\"dropdown-toggle\"");

WriteLiteral(" data-toggle=\"dropdown\"");

WriteLiteral(" role=\"button\"");

WriteLiteral(" aria-haspopup=\"true\"");

WriteLiteral(" aria-expanded=\"false\"");

WriteLiteral(">Managment<span");

WriteLiteral(" class=\"caret\"");

WriteLiteral("></span></a>\r\n                        <ul");

WriteLiteral(" class=\"dropdown-menu\"");

WriteLiteral(">\r\n                            <li>");

            
            #line 69 "..\..\Views\Shared\_Layout.cshtml"
                           Write(Html.ActionLink("Car models", "List", "CarModel", new { area = "" }, new { @class = "" }));

            
            #line default
            #line hidden
WriteLiteral("</li>\r\n                            <li>");

            
            #line 70 "..\..\Views\Shared\_Layout.cshtml"
                           Write(Html.ActionLink("Car body types", "List", "CarBodyType", new { area = "" }, new { @class = "" }));

            
            #line default
            #line hidden
WriteLiteral("</li>\r\n                            <li>");

            
            #line 71 "..\..\Views\Shared\_Layout.cshtml"
                           Write(Html.ActionLink("Car options", "List", "CarOption", new { area = "" }, new { @class = "" }));

            
            #line default
            #line hidden
WriteLiteral("</li>\r\n                            <li>");

            
            #line 72 "..\..\Views\Shared\_Layout.cshtml"
                           Write(Html.ActionLink("Manufacturers", "List", "Manufacturer", new { area = "" }, new { @class = "" }));

            
            #line default
            #line hidden
WriteLiteral("</li>\r\n                            <li>");

            
            #line 73 "..\..\Views\Shared\_Layout.cshtml"
                           Write(Html.ActionLink("Countries", "List", "Country", new { area = "" }, new { @class = "" }));

            
            #line default
            #line hidden
WriteLiteral("</li>\r\n                            <li>");

            
            #line 74 "..\..\Views\Shared\_Layout.cshtml"
                           Write(Html.ActionLink("Car fuel types", "List", "FuelType", new { area = "" }, new { @class = "" }));

            
            #line default
            #line hidden
WriteLiteral("</li>\r\n                            <li>");

            
            #line 75 "..\..\Views\Shared\_Layout.cshtml"
                           Write(Html.ActionLink("Car transmition types", "List", "TransmitionType", new { area = "" }, new { @class = "" }));

            
            #line default
            #line hidden
WriteLiteral("</li>\r\n                            <li");

WriteLiteral(" role=\"separator\"");

WriteLiteral(" class=\"divider\"");

WriteLiteral("></li>\r\n                            <li>");

            
            #line 77 "..\..\Views\Shared\_Layout.cshtml"
                           Write(Html.ActionLink("Users", "List", "User", new { area = "" }, new { @class = "" }));

            
            #line default
            #line hidden
WriteLiteral("</li>\r\n                            <li>");

            
            #line 78 "..\..\Views\Shared\_Layout.cshtml"
                           Write(Html.ActionLink("Roles", "List", "Role", new { area = "" }, new { @class = "" }));

            
            #line default
            #line hidden
WriteLiteral("</li>\r\n                        </ul>\r\n                    </li>\r\n");

            
            #line 81 "..\..\Views\Shared\_Layout.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("                <li>\r\n");

WriteLiteral("                    ");

            
            #line 83 "..\..\Views\Shared\_Layout.cshtml"
               Write(Html.Select2Search(new { @class = "select2Search" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </li>\r\n            </ul>\r\n");

WriteLiteral("            ");

            
            #line 86 "..\..\Views\Shared\_Layout.cshtml"
       Write(Html.Partial("_LoginPartial"));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n    </nav>\r\n\r\n\r\n    <div");

WriteLiteral(" class=\"container body-content\"");

WriteLiteral(">\r\n");

WriteLiteral("        ");

            
            #line 92 "..\..\Views\Shared\_Layout.cshtml"
   Write(RenderBody());

            
            #line default
            #line hidden
WriteLiteral("\r\n        <hr />\r\n        <div");

WriteLiteral(" class=\"notifications\"");

WriteLiteral(">\r\n        </div>\r\n        <footer>\r\n            <p>&copy; ");

            
            #line 97 "..\..\Views\Shared\_Layout.cshtml"
                 Write(DateTime.Now.Year);

            
            #line default
            #line hidden
WriteLiteral(" - My ASP.NET Application</p>\r\n        </footer>\r\n    </div>\r\n</body>\r\n</html>");

        }
    }
}
#pragma warning restore 1591
