#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using AutoSiteProject.UI;
    using DevExpress.Utils;
    using DevExpress.Web;
    using DevExpress.Web.ASPxThemes;
    using DevExpress.Web.Mvc;
    using DevExpress.Web.Mvc.UI;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/_Layout.cshtml")]
    public partial class _Views_Shared__Layout_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Shared__Layout_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<!DOCTYPE html>\r\n<html>\r\n<head>\r\n    <meta");

WriteLiteral(" charset=\"utf-8\"");

WriteLiteral(" />\r\n    <meta");

WriteLiteral(" name=\"viewport\"");

WriteLiteral(" content=\"width=device-width, initial-scale=1.0\"");

WriteLiteral(">\r\n    <title>");

            
            #line 6 "..\..\Views\Shared\_Layout.cshtml"
      Write(ViewBag.Title);

            
            #line default
            #line hidden
WriteLiteral(" - My ASP.NET Application</title>\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 208), Tuple.Create("\"", 233)
, Tuple.Create(Tuple.Create("", 215), Tuple.Create<System.Object, System.Int32>(Href("~/Content/Site.css")
, 215), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(" />\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 281), Tuple.Create("\"", 315)
, Tuple.Create(Tuple.Create("", 288), Tuple.Create<System.Object, System.Int32>(Href("~/Content/bootstrap.min.css")
, 288), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(" />\r\n    \r\n   \r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 376), Tuple.Create("\"", 412)
, Tuple.Create(Tuple.Create("", 382), Tuple.Create<System.Object, System.Int32>(Href("~/scripts/jquery-1.10.2.min.js")
, 382), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 436), Tuple.Create("\"", 474)
, Tuple.Create(Tuple.Create("", 442), Tuple.Create<System.Object, System.Int32>(Href("~/scripts/jquery.validate.min.js")
, 442), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 498), Tuple.Create("\"", 548)
, Tuple.Create(Tuple.Create("", 504), Tuple.Create<System.Object, System.Int32>(Href("~/scripts/jquery.validate.unobtrusive.min.js")
, 504), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 572), Tuple.Create("\"", 618)
, Tuple.Create(Tuple.Create("", 578), Tuple.Create<System.Object, System.Int32>(Href("~/scripts/jquery.unobtrusive-ajax.min.js")
, 578), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 642), Tuple.Create("\"", 676)
, Tuple.Create(Tuple.Create("", 648), Tuple.Create<System.Object, System.Int32>(Href("~/scripts/modernizr-2.7.2.js")
, 648), false)
);

WriteLiteral("></script>\r\n\r\n");

WriteLiteral("    ");

            
            #line 17 "..\..\Views\Shared\_Layout.cshtml"
Write(Html.DevExpress().GetScripts(
        //new Script { ExtensionSuite = ExtensionSuite.NavigationAndLayout },
        //new Script { ExtensionSuite = ExtensionSuite.HtmlEditor },
        //new Script { ExtensionSuite = ExtensionSuite.PivotGrid },
        //new Script { ExtensionSuite = ExtensionSuite.Editors },
        //new Script { ExtensionSuite = ExtensionSuite.Chart },
        //new Script { ExtensionSuite = ExtensionSuite.Report },
        new Script { ExtensionSuite = ExtensionSuite.Scheduler },
        //new Script { ExtensionSuite = ExtensionSuite.TreeList },
        //new Script { ExtensionSuite = ExtensionSuite.Spreadsheet },
        //new Script { ExtensionSuite = ExtensionSuite.RichEdit },
        //new Script { ExtensionSuite = ExtensionSuite.SpellChecker },
        new Script { ExtensionSuite = ExtensionSuite.GridView }

    ));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 32 "..\..\Views\Shared\_Layout.cshtml"
Write(Html.DevExpress().GetStyleSheets(
        //new StyleSheet { ExtensionSuite = ExtensionSuite.NavigationAndLayout },
        //new StyleSheet { ExtensionSuite = ExtensionSuite.Editors },
        //new StyleSheet { ExtensionSuite = ExtensionSuite.HtmlEditor },
        //new StyleSheet { ExtensionSuite = ExtensionSuite.PivotGrid },
        //new StyleSheet { ExtensionSuite = ExtensionSuite.Chart },
        //new StyleSheet { ExtensionSuite = ExtensionSuite.Report },
        new StyleSheet { ExtensionSuite = ExtensionSuite.Scheduler },
        //new StyleSheet { ExtensionSuite = ExtensionSuite.TreeList },
        //new StyleSheet { ExtensionSuite = ExtensionSuite.Spreadsheet },
        //new StyleSheet { ExtensionSuite = ExtensionSuite.RichEdit },
        //new StyleSheet { ExtensionSuite = ExtensionSuite.SpellChecker },
        new StyleSheet { ExtensionSuite = ExtensionSuite.GridView }

    ));

            
            #line default
            #line hidden
WriteLiteral("\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 2498), Tuple.Create("\"", 2530)
, Tuple.Create(Tuple.Create("", 2504), Tuple.Create<System.Object, System.Int32>(Href("~/scripts/bootstrap.min.js")
, 2504), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 2554), Tuple.Create("\"", 2597)
, Tuple.Create(Tuple.Create("", 2560), Tuple.Create<System.Object, System.Int32>(Href("~/scripts/AutoSite/MySelect2Search.js")
, 2560), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 2621), Tuple.Create("\"", 2664)
, Tuple.Create(Tuple.Create("", 2627), Tuple.Create<System.Object, System.Int32>(Href("~/scripts/jquery.signalR-2.2.0.min.js")
, 2627), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 2688), Tuple.Create("\"", 2708)
, Tuple.Create(Tuple.Create("", 2694), Tuple.Create<System.Object, System.Int32>(Href("~/signalr/hubs")
, 2694), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 2732), Tuple.Create("\"", 2773)
, Tuple.Create(Tuple.Create("", 2738), Tuple.Create<System.Object, System.Int32>(Href("~/scripts/AutoSite/Notifications.js")
, 2738), false)
);

WriteLiteral("></script>\r\n</head>\r\n<body>\r\n    <nav");

WriteLiteral(" class=\"navbar navbar-inverse navbar-fixed-top\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"navbar-collapse collapse\"");

WriteLiteral(">\r\n            <ul");

WriteLiteral(" class=\"nav navbar-nav\"");

WriteLiteral(">\r\n                <li>");

            
            #line 57 "..\..\Views\Shared\_Layout.cshtml"
               Write(Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "" }));

            
            #line default
            #line hidden
WriteLiteral("</li>\r\n                <li>");

            
            #line 58 "..\..\Views\Shared\_Layout.cshtml"
               Write(Html.ActionLink("Cars", "List", "CarItem", new { area = "" }, new { @class = "" }));

            
            #line default
            #line hidden
WriteLiteral("</li>\r\n");

            
            #line 59 "..\..\Views\Shared\_Layout.cshtml"
                
            
            #line default
            #line hidden
            
            #line 59 "..\..\Views\Shared\_Layout.cshtml"
                 if (User.IsInRole("Admin"))
                {

            
            #line default
            #line hidden
WriteLiteral("                    <li");

WriteLiteral(" class=\"dropdown\"");

WriteLiteral(">\r\n                        <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" class=\"dropdown-toggle\"");

WriteLiteral(" data-toggle=\"dropdown\"");

WriteLiteral(" role=\"button\"");

WriteLiteral(" aria-haspopup=\"true\"");

WriteLiteral(" aria-expanded=\"false\"");

WriteLiteral(">Managment<span");

WriteLiteral(" class=\"caret\"");

WriteLiteral("></span></a>\r\n                        <ul");

WriteLiteral(" class=\"dropdown-menu\"");

WriteLiteral(">\r\n                            <li>");

            
            #line 64 "..\..\Views\Shared\_Layout.cshtml"
                           Write(Html.ActionLink("Car models", "List", "CarModel", new { area = "" }, new { @class = "" }));

            
            #line default
            #line hidden
WriteLiteral("</li>\r\n                            <li>");

            
            #line 65 "..\..\Views\Shared\_Layout.cshtml"
                           Write(Html.ActionLink("Car body types", "List", "CarBodyType", new { area = "" }, new { @class = "" }));

            
            #line default
            #line hidden
WriteLiteral("</li>\r\n                            <li>");

            
            #line 66 "..\..\Views\Shared\_Layout.cshtml"
                           Write(Html.ActionLink("Car options", "List", "CarOption", new { area = "" }, new { @class = "" }));

            
            #line default
            #line hidden
WriteLiteral("</li>\r\n                            <li>");

            
            #line 67 "..\..\Views\Shared\_Layout.cshtml"
                           Write(Html.ActionLink("Manufacturers", "List", "Manufacturer", new { area = "" }, new { @class = "" }));

            
            #line default
            #line hidden
WriteLiteral("</li>\r\n                            <li>");

            
            #line 68 "..\..\Views\Shared\_Layout.cshtml"
                           Write(Html.ActionLink("Countries", "List", "Country", new { area = "" }, new { @class = "" }));

            
            #line default
            #line hidden
WriteLiteral("</li>\r\n                            <li");

WriteLiteral(" role=\"separator\"");

WriteLiteral(" class=\"divider\"");

WriteLiteral("></li>\r\n                            <li>");

            
            #line 70 "..\..\Views\Shared\_Layout.cshtml"
                           Write(Html.ActionLink("Users", "List", "User", new { area = "" }, new { @class = "" }));

            
            #line default
            #line hidden
WriteLiteral("</li>\r\n                            <li>");

            
            #line 71 "..\..\Views\Shared\_Layout.cshtml"
                           Write(Html.ActionLink("Roles", "List", "Role", new { area = "" }, new { @class = "" }));

            
            #line default
            #line hidden
WriteLiteral("</li>\r\n                        </ul>\r\n                    </li>\r\n");

            
            #line 74 "..\..\Views\Shared\_Layout.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("            </ul>\r\n");

WriteLiteral("            ");

            
            #line 76 "..\..\Views\Shared\_Layout.cshtml"
       Write(Html.Partial("_LoginPartial"));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n    </nav>\r\n\r\n\r\n    <div");

WriteLiteral(" class=\"container body-content\"");

WriteLiteral(">\r\n");

WriteLiteral("        ");

            
            #line 82 "..\..\Views\Shared\_Layout.cshtml"
   Write(RenderBody());

            
            #line default
            #line hidden
WriteLiteral("\r\n        <hr />\r\n        <div");

WriteLiteral(" class=\"notifications\"");

WriteLiteral(">\r\n        </div>\r\n        <footer>\r\n            <p>&copy; ");

            
            #line 87 "..\..\Views\Shared\_Layout.cshtml"
                 Write(DateTime.Now.Year);

            
            #line default
            #line hidden
WriteLiteral(" - My ASP.NET Application</p>\r\n        </footer>\r\n    </div>\r\n</body>\r\n</html>");

        }
    }
}
#pragma warning restore 1591
