#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    
    #line 1 "..\..\Views\DataLoader\CarsGridViewPartial.cshtml"
    using System.Web.UI.WebControls;
    
    #line default
    #line hidden
    using System.Web.WebPages;
    
    #line 2 "..\..\Views\DataLoader\CarsGridViewPartial.cshtml"
    using AutoSiteProject.Models.ViewModels;
    
    #line default
    #line hidden
    using AutoSiteProject.UI;
    using DevExpress.Utils;
    using DevExpress.Web;
    using DevExpress.Web.ASPxThemes;
    using DevExpress.Web.Mvc;
    using DevExpress.Web.Mvc.UI;
    
    #line 3 "..\..\Views\DataLoader\CarsGridViewPartial.cshtml"
    using Microsoft.AspNet.Identity;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/DataLoader/CarsGridViewPartial.cshtml")]
    public partial class _Views_DataLoader_CarsGridViewPartial_cshtml : System.Web.Mvc.WebViewPage<IEnumerable<CarAggregateViewModel>>
    {
        public _Views_DataLoader_CarsGridViewPartial_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 5 "..\..\Views\DataLoader\CarsGridViewPartial.cshtml"
Write(Html.DevExpress().GridView(settings =>
{
    settings.Name = "carsGridView";
    settings.CallbackRouteValues = new { Controller = "DataLoader", Action = "GetCarsPartial" };
    settings.Width = Unit.Percentage(100);


    //settings.Columns.Add("CarId");

    settings.Columns.Add("Country");
    settings.Columns.Add("Manufacturer");
    settings.Columns.Add("Model");
    settings.Columns.Add("BodyType","Body type");
    settings.Columns.Add("FuelType","Fuel type");
    settings.Columns.Add("TransmitionType","Transmition type");
    settings.Columns.Add("Price");
    settings.Columns.Add("ReleaseYear","Release year");
    settings.Columns.Add("Volume","Engine volume");
    settings.Columns.Add("Description");
    settings.Columns.Add("OptionsNamesString", "Options");
    settings.Columns.Add(column =>
    {
        column.Caption = "#";
        column.SetDataItemTemplateContent(c =>
        {
            ViewContext.Writer.Write(
                Html.ActionLink("Details", "Details", "CarItem", routeValues: new { Id = DataBinder.Eval(c.DataItem, "CarId") }, htmlAttributes: new { })
                + "&nbsp;");
            var userId = User.Identity.GetUserId();
            if ((DataBinder.Eval(c.DataItem, "OwnerId").ToString() == userId &&  ((CarItemStatus)DataBinder.Eval(c.DataItem, "Status")) == CarItemStatus.Open) || User.IsInRole("Admin"))
                ViewContext.Writer.Write(
                        Html.ActionLink("Edit", "Edit", "CarItem", routeValues: new { Id = DataBinder.Eval(c.DataItem, "CarId") }, htmlAttributes: new { })
                        + "&nbsp;" +
                        Html.ActionLink("Close", "SetStatusToClose", "CarItem", routeValues: new { Id = DataBinder.Eval(c.DataItem, "CarId") }, htmlAttributes: new { })
                        );
        });
        column.SetHeaderTemplateContent(c =>
        {
            ViewContext.Writer.Write(
                Html.ActionLink("New", "Create", "CarItem").ToHtmlString()
                );
        });
        column.Settings.AllowDragDrop = DefaultBoolean.False;
        column.Settings.AllowSort = DefaultBoolean.False;
        column.Width = 70;
    });
    settings.Settings.ShowGroupPanel = true;
    settings.KeyFieldName = "CarId";
    settings.ClientSideEvents.BeginCallback = "carFilter.onBeginCallback";
    settings.SettingsPager.PageSize = 25;
}).Bind(Model).GetHtml());

            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
