#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using AutoSiteProject.UI;
    using DevExpress.Utils;
    using DevExpress.Web;
    using DevExpress.Web.ASPxThemes;
    using DevExpress.Web.Mvc;
    using DevExpress.Web.Mvc.UI;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/CarItem/Edit.cshtml")]
    public partial class _Views_CarItem_Edit_cshtml : System.Web.Mvc.WebViewPage<AutoSiteProject.Models.ViewModels.CarItemViewModel>
    {
        public _Views_CarItem_Edit_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<script");

WriteAttribute("src", Tuple.Create(" src=\"", 68), Tuple.Create("\"", 107)
, Tuple.Create(Tuple.Create("", 74), Tuple.Create<System.Object, System.Int32>(Href("~/scripts/AutoSite/ImageLoader.js")
, 74), false)
);

WriteLiteral("></script>\r\n<link");

WriteAttribute("href", Tuple.Create(" href=\"", 125), Tuple.Create("\"", 164)
, Tuple.Create(Tuple.Create("", 132), Tuple.Create<System.Object, System.Int32>(Href("~/Content/MyCss/WidthClasses.css")
, 132), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n<link");

WriteAttribute("href", Tuple.Create(" href=\"", 192), Tuple.Create("\"", 230)
, Tuple.Create(Tuple.Create("", 199), Tuple.Create<System.Object, System.Int32>(Href("~/Content/MyCss/CloseButton.css")
, 199), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral("/>\r\n<input");

WriteLiteral(" type=\"button\"");

WriteLiteral(" value=\"Close advertisment\"");

WriteAttribute("onclick", Tuple.Create(" onclick=\"", 299), Tuple.Create("\"", 351)
            
            #line 6 "..\..\Views\CarItem\Edit.cshtml"
, Tuple.Create(Tuple.Create("", 309), Tuple.Create<System.Object, System.Int32>(Url.Action("SetStatusToClose", "CarItem")
            
            #line default
            #line hidden
, 309), false)
);

WriteLiteral(" class=\"btn btn-default adv-close-btn\"");

WriteLiteral(" />\r\n\r\n<h3>Edit car</h3> \r\n<hr/>\r\n    \r\n");

            
            #line 11 "..\..\Views\CarItem\Edit.cshtml"
 using (Html.BeginForm("Edit", "CarItem", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    
            
            #line default
            #line hidden
            
            #line 13 "..\..\Views\CarItem\Edit.cshtml"
Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
            
            #line 13 "..\..\Views\CarItem\Edit.cshtml"
                            


            
            #line default
            #line hidden
WriteLiteral("    <div");

WriteLiteral(" class=\"form-horizontal\"");

WriteLiteral(">\r\n");

            
            #line 16 "..\..\Views\CarItem\Edit.cshtml"
        
            
            #line default
            #line hidden
            
            #line 16 "..\..\Views\CarItem\Edit.cshtml"
           Html.RenderPartial("_CarItem", Model);
            
            #line default
            #line hidden
WriteLiteral("\r\n        <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"col-md-offset-2 col-md-10\"");

WriteLiteral(">\r\n                <input");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" value=\"Save\"");

WriteLiteral(" class=\"btn btn-default\"");

WriteLiteral("/>\r\n            </div>\r\n            \r\n        </div>\r\n    </div>\r\n");

            
            #line 24 "..\..\Views\CarItem\Edit.cshtml"
}

            
            #line default
            #line hidden
WriteLiteral("\r\n<div>\r\n");

WriteLiteral("    ");

            
            #line 27 "..\..\Views\CarItem\Edit.cshtml"
Write(Html.ActionLink("Back to previous page", null, null, null, new { href = Request.UrlReferrer }));

            
            #line default
            #line hidden
WriteLiteral("\r\n</div>\r\n\r\n\r\n\r\n\r\n");

        }
    }
}
#pragma warning restore 1591
