#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Views\Home\Index.cshtml"
    using AutoSiteProject.Models.ViewModels;
    
    #line default
    #line hidden
    using AutoSiteProject.UI;
    using DevExpress.Utils;
    using DevExpress.Web;
    using DevExpress.Web.ASPxThemes;
    using DevExpress.Web.Mvc;
    using DevExpress.Web.Mvc.UI;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Home/Index.cshtml")]
    public partial class _Views_Home_Index_cshtml : System.Web.Mvc.WebViewPage<IEnumerable<CarAggregateViewModel>>
    {
        public _Views_Home_Index_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 4 "..\..\Views\Home\Index.cshtml"
  
    ViewBag.Title = "Index";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<h2>Index</h2>\r\n");

            
            #line 9 "..\..\Views\Home\Index.cshtml"
Write(Html.Partial("_CarFilter", (CarAggregateFilterViewModel)ViewBag.CarFilter));

            
            #line default
            #line hidden
WriteLiteral("\r\n<table");

WriteLiteral(" class=\"table cars-result\"");

WriteLiteral(">\r\n    <tr>\r\n        <th>\r\n");

WriteLiteral("            ");

            
            #line 13 "..\..\Views\Home\Index.cshtml"
       Write(Html.DisplayNameFor(model => model.CarId));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </th>\r\n        <th>\r\n");

WriteLiteral("            ");

            
            #line 16 "..\..\Views\Home\Index.cshtml"
       Write(Html.DisplayNameFor(model => model.Country));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </th>\r\n        <th>\r\n");

WriteLiteral("            ");

            
            #line 19 "..\..\Views\Home\Index.cshtml"
       Write(Html.DisplayNameFor(model => model.Manufacturer));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </th>\r\n        <th>\r\n");

WriteLiteral("            ");

            
            #line 22 "..\..\Views\Home\Index.cshtml"
       Write(Html.DisplayNameFor(model => model.Model));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </th>\r\n        <th>\r\n");

WriteLiteral("            ");

            
            #line 25 "..\..\Views\Home\Index.cshtml"
       Write(Html.DisplayNameFor(model => model.BodyType));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </th>\r\n        <th>\r\n");

WriteLiteral("            ");

            
            #line 28 "..\..\Views\Home\Index.cshtml"
       Write(Html.DisplayNameFor(model => model.Options));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </th>\r\n        <th>\r\n");

WriteLiteral("            ");

            
            #line 31 "..\..\Views\Home\Index.cshtml"
       Write(Html.DisplayNameFor(model => model.Description));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </th>\r\n\r\n    </tr>\r\n\r\n");

            
            #line 36 "..\..\Views\Home\Index.cshtml"
    
            
            #line default
            #line hidden
            
            #line 36 "..\..\Views\Home\Index.cshtml"
     foreach (var item in Model)
    {

            
            #line default
            #line hidden
WriteLiteral("    <tr>\r\n        <td>\r\n");

WriteLiteral("            ");

            
            #line 40 "..\..\Views\Home\Index.cshtml"
       Write(Html.DisplayFor(modelItem => item.CarId));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </td>\r\n        <td>\r\n");

WriteLiteral("            ");

            
            #line 43 "..\..\Views\Home\Index.cshtml"
       Write(Html.DisplayFor(modelItem => item.Country));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </td>\r\n        <td>\r\n");

WriteLiteral("            ");

            
            #line 46 "..\..\Views\Home\Index.cshtml"
       Write(Html.DisplayFor(modelItem => item.Manufacturer));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </td>\r\n        <td>\r\n");

WriteLiteral("            ");

            
            #line 49 "..\..\Views\Home\Index.cshtml"
       Write(Html.DisplayFor(modelItem => item.Model));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </td>\r\n        <td>\r\n");

WriteLiteral("            ");

            
            #line 52 "..\..\Views\Home\Index.cshtml"
       Write(Html.DisplayFor(modelItem => item.BodyType));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </td>\r\n        <td>\r\n");

            
            #line 55 "..\..\Views\Home\Index.cshtml"
            
            
            #line default
            #line hidden
            
            #line 55 "..\..\Views\Home\Index.cshtml"
             foreach (var opt in item.OptionsNames)
                {
                
            
            #line default
            #line hidden
            
            #line 57 "..\..\Views\Home\Index.cshtml"
           Write(Html.Label(opt));

            
            #line default
            #line hidden
            
            #line 57 "..\..\Views\Home\Index.cshtml"
                                
                    if (item.OptionsNames.IndexOf(opt) != item.OptionsNames.Count - 1)
                    { 
            
            #line default
            #line hidden
            
            #line 59 "..\..\Views\Home\Index.cshtml"
                 Write(Html.Label(", "));

            
            #line default
            #line hidden
            
            #line 59 "..\..\Views\Home\Index.cshtml"
                                       }
                }

            
            #line default
            #line hidden
WriteLiteral("        </td>\r\n        <td>\r\n");

WriteLiteral("            ");

            
            #line 63 "..\..\Views\Home\Index.cshtml"
       Write(Html.DisplayFor(modelItem => item.Description));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </td>\r\n    </tr>\r\n");

            
            #line 66 "..\..\Views\Home\Index.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("\r\n</table>\r\n");

            
            #line 69 "..\..\Views\Home\Index.cshtml"
Write(Html.Action("GetCarsParial","DataLoader", new { ViewBag.CarFilter}));

            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
