#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 3 "..\..\Views\Home\Index.cshtml"
    using AutoSiteProject.Models.ViewModels;
    
    #line default
    #line hidden
    using AutoSiteProject.UI;
    using DevExpress.Utils;
    using DevExpress.Web;
    using DevExpress.Web.ASPxThemes;
    using DevExpress.Web.Mvc;
    using DevExpress.Web.Mvc.UI;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Home/Index.cshtml")]
    public partial class _Views_Home_Index_cshtml : System.Web.Mvc.WebViewPage<IEnumerable<CarAggregateViewModel>>
    {
        public _Views_Home_Index_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<link");

WriteAttribute("href", Tuple.Create(" href=\"", 5), Tuple.Create("\"", 45)
, Tuple.Create(Tuple.Create("", 12), Tuple.Create<System.Object, System.Int32>(Href("~/Content/MyCss/MainPageStyle.css")
, 12), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n\r\n");

WriteLiteral("<hr />\r\n");

            
            #line 6 "..\..\Views\Home\Index.cshtml"
   Html.RenderPartial("_CarFilter", (CarAggregateFilterViewModel)ViewBag.CarFilter);
            
            #line default
            #line hidden
WriteLiteral("\r\n<div");

WriteLiteral(" class=\"deControl\"");

WriteLiteral(">\r\n");

            
            #line 8 "..\..\Views\Home\Index.cshtml"
    
            
            #line default
            #line hidden
            
            #line 8 "..\..\Views\Home\Index.cshtml"
       Html.RenderAction("GetCarsPartial", "DataLoader");
            
            #line default
            #line hidden
WriteLiteral("\r\n</div>");

        }
    }
}
#pragma warning restore 1591
